name: MLflow Project CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Create directories if they don't exist
        mkdir -p data models
        pytest -v

  train-model:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Check network connectivity
      run: |
        echo "Checking network connectivity..."
        curl -s -o /dev/null -w "HTTP Status Code for github.com: %{http_code}\n" https://github.com
        
    - name: Create dummy file for prefetch
      run: |
        echo "dummy content" > dummy.txt

    # Prefetch the action to avoid download issues
    - name: Prefetch upload-artifact action
      uses: actions/upload-artifact@v4
      with:
        name: dummy
        path: dummy.txt
        retention-days: 1
      continue-on-error: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Train model
      run: |
        # Create directories if they don't exist
        mkdir -p data models
        python train.py
        
        # Backup mlruns folder to upload as artifact if it exists and is not empty
        if [ -d "mlruns" ] && [ "$(ls -A mlruns 2>/dev/null)" ]; then
          echo "Backing up mlruns directory for MLflow UI"
          zip -r mlruns_backup.zip mlruns
        else
          echo "No mlruns directory found or it's empty"
        fi

    - name: Create artifact archive
      run: |
        mkdir -p artifact_bundle
        # Copy model files and scaler
        cp -r models/* artifact_bundle/ || echo "No model files to copy"
        cp data/scaler.joblib artifact_bundle/ || echo "scaler.joblib not found"
        # Copy mlruns backup for MLflow UI if it exists
        [ -f mlruns_backup.zip ] && cp mlruns_backup.zip artifact_bundle/
        # Ensure artifact directory is not empty
        if [ -z "$(ls -A artifact_bundle)" ]; then
          echo "Creating placeholder file"
          echo "placeholder" > artifact_bundle/placeholder.txt
        fi

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: artifact_bundle/
        retention-days: 5

  deploy-to-huggingface:
    runs-on: ubuntu-latest
    needs: train-model
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: downloaded_artifacts

    - name: Setup artifacts 
      run: |
        # Setup directories and copy artifacts
        mkdir -p models data
        
        # Check if downloaded_artifacts directory is not empty
        if [ "$(ls -A downloaded_artifacts 2>/dev/null)" ]; then
          # Copy model files but skip mlruns_backup.zip
          for file in downloaded_artifacts/*; do
            if [[ "$file" != *"mlruns_backup.zip" ]]; then
              cp -r "$file" models/ || echo "Could not copy $file to models directory"
            fi
          done
          
          # Handle scaler.joblib separately
          if [ -f downloaded_artifacts/scaler.joblib ]; then
            mv downloaded_artifacts/scaler.joblib data/
          fi
        else
          echo "Warning: downloaded_artifacts directory is empty or does not exist"
        fi
        
        # Show directories for debugging
        echo "Models directory contents:"
        ls -la models/ || echo "Models directory is empty"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install huggingface_hub

    - name: Prepare deployment for Hugging Face
      run: |
        # Create deployment directory
        mkdir -p huggingface_app
        
        # Copy app and requirements
        cp -r app/* huggingface_app/ || echo "Error copying app files"
        cp requirements.txt huggingface_app/ || echo "requirements.txt not found"
        
        # Copy README from templates
        if [ -f .github/hf_templates/app_README.md ]; then
          cp .github/hf_templates/app_README.md huggingface_app/README.md
        fi
        
        # Copy Dockerfile
        if [ -f .github/hf_templates/app_Dockerfile ]; then
          cp .github/hf_templates/app_Dockerfile huggingface_app/Dockerfile
        fi
        
        # Copy .gitattributes if exists
        if [ -f .github/hf_templates/.gitattributes ]; then
          cp .github/hf_templates/.gitattributes huggingface_app/
        fi
        
        # Copy documentation if available
        if [ -f ProjectDescription.md ]; then
          cp ProjectDescription.md huggingface_app/
        elif [ -f app/ProjectDescription.md ]; then
          cp app/ProjectDescription.md huggingface_app/
        fi
        
        # Handle model files
        mkdir -p huggingface_app/models huggingface_app/data
        chmod -R 755 huggingface_app/models huggingface_app/data
        
        if [ -f models/model.joblib ]; then
          cp models/model.joblib huggingface_app/models/best_model.joblib
        elif [ -f models/best_model.pkl ]; then
          cp models/best_model.pkl huggingface_app/models/best_model.joblib
        else
          cp -r models/* huggingface_app/models/ || echo "No model files found"
          # Create placeholder if needed
          [ -z "$(ls -A huggingface_app/models)" ] && echo "Placeholder model" > huggingface_app/models/best_model.joblib
        fi
        
        # Copy scaler
        cp data/scaler.joblib huggingface_app/data/ || echo "No scaler.joblib to copy"
        
        # Replace username placeholder in README
        [ -f huggingface_app/README.md ] && sed -i "s/{username}/$HF_USERNAME/g" huggingface_app/README.md

    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        # Setup tools and environment
        pip install huggingface_hub
        sudo apt-get update && sudo apt-get install -y git-lfs
        git config --global user.email "${{ secrets.EMAIL_HUGGINGFACE }}"
        git config --global user.name "${{ secrets.USERNAME_HUGGINGFACE }}"
        
        # Login and validate
        huggingface-cli login --token $HF_TOKEN
        [ -z "$HF_USERNAME" ] && echo "Error: HF_USERNAME not set in secrets" && exit 1
        
        # Try creating the space silently first, ignore errors if it already exists
        echo "Creating or checking Hugging Face Space..."
        huggingface-cli repo create "spaces/$HF_USERNAME/mlflow-project-app" --type space || echo "Space might already exist"
        
        # Setup Git repository and LFS
        cd huggingface_app
        git init
        git lfs install
        
        # Configure Git LFS to track binary files
        git lfs track "*.joblib" "*.pkl" "*.h5" "*.onnx" "*.bin" "*.zip" "*.gz" "*.tar"
        
        # Make sure .gitattributes is tracked by git
        git add .gitattributes
        
        # Check for and remove any binary files that shouldn't be deployed
        if [ -f "models/mlruns_backup.zip" ]; then
          echo "Removing mlruns_backup.zip from models directory"
          rm models/mlruns_backup.zip
        fi
        
        # Checkout, add files, commit and push
        git checkout -b main
        git add .
        git commit -m "Deploy MLflow Project to Hugging Face Spaces"
        
        # Setup remote and push
        git remote add origin "https://huggingface.co/spaces/$HF_USERNAME/mlflow-project-app"
        git push -f "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/mlflow-project-app" main

  deploy-mlflow-ui:
    runs-on: ubuntu-latest
    needs: train-model
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: downloaded_artifacts

    - name: Setup artifacts and mlruns
      run: |
        # Setup directories and copy artifacts
        mkdir -p models data mlruns
        
        # Check if downloaded_artifacts directory is not empty
        if [ "$(ls -A downloaded_artifacts 2>/dev/null)" ]; then
          # Copy model files
          cp -r downloaded_artifacts/* models/ || echo "No files to copy to models directory"
          
          # Move scaler.joblib to data directory if it exists
          if [ -f downloaded_artifacts/scaler.joblib ]; then
            mv downloaded_artifacts/scaler.joblib data/
          fi
          
          # Restore mlruns from backup if it exists
          if [ -f downloaded_artifacts/mlruns_backup.zip ]; then
            echo "Restoring mlruns from backup"
            unzip -o downloaded_artifacts/mlruns_backup.zip -d ./ || echo "Failed to extract mlruns"
            
            # Check if mlruns was successfully restored
            if [ -d "mlruns" ] && [ "$(ls -A mlruns 2>/dev/null)" ]; then
              echo "MLflow data successfully restored"
            else
              echo "Warning: Failed to restore MLflow data properly"
            fi
          else
            echo "No mlruns backup found in artifacts"
          fi
        else
          echo "Warning: downloaded_artifacts directory is empty or does not exist"
        fi
        
        # Show content of mlruns directory
        echo "Current mlruns directory structure:"
        ls -la mlruns/ || echo "mlruns directory is empty or doesn't exist"
        
        # Create minimal mlruns structure if it doesn't exist
        if [ ! -d "mlruns" ] || [ -z "$(ls -A mlruns 2>/dev/null)" ]; then
          echo "Creating minimal mlruns structure"
          mkdir -p mlruns/0
          echo '{"experiment_id": "0", "name": "Default", "artifact_location": "mlruns/0", "lifecycle_stage": "active"}' > mlruns/0/meta.yaml
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install huggingface_hub mlflow

    - name: Prepare MLflow UI deployment
      run: |
        # Create deployment directory
        mkdir -p mlflow_ui_app
        
        # Copy template files
        cp .github/hf_templates/app.py mlflow_ui_app/
        cp .github/hf_templates/setup_mlflow.py mlflow_ui_app/
        [ -f .github/hf_templates/mlflow_ui_Dockerfile ] && cp .github/hf_templates/mlflow_ui_Dockerfile mlflow_ui_app/Dockerfile
        [ -f .github/hf_templates/mlflow_ui_README.md ] && cp .github/hf_templates/mlflow_ui_README.md mlflow_ui_app/README.md
        cp .github/hf_templates/.gitattributes mlflow_ui_app/
        
        # Copy requirements and ensure MLflow is included
        cp requirements.txt mlflow_ui_app/
        grep -q "mlflow" mlflow_ui_app/requirements.txt || echo "mlflow==2.8.0" >> mlflow_ui_app/requirements.txt
        grep -q "scikit-learn" mlflow_ui_app/requirements.txt || echo "scikit-learn==1.2.2" >> mlflow_ui_app/requirements.txt
        grep -q "numpy" mlflow_ui_app/requirements.txt || echo "numpy==1.23.5" >> mlflow_ui_app/requirements.txt
        
        # Remove any leftover backup files
        rm -f models/mlruns_backup.zip downloaded_artifacts/mlruns_backup.zip 2>/dev/null || true
        
        # Prepare mlruns directory for MLflow UI app
        mkdir -p mlflow_ui_app/mlruns/.trash
        touch mlflow_ui_app/mlruns/.trash/.gitkeep
        
        # Copy mlruns directory if it exists and has data
        if [ -d "mlruns" ] && [ "$(find mlruns -mindepth 1 -not -path "*/\.*" | wc -l)" -gt 0 ]; then
          echo "Copying MLflow data to UI app"
          
          # Copy all experiment directories except .trash
          for dir in mlruns/*/; do
            if [[ "$dir" != "mlruns/.trash/" && -d "$dir" ]]; then
              exp_name=$(basename "$dir")
              echo "Copying experiment: $exp_name"
              mkdir -p "mlflow_ui_app/mlruns/$exp_name"
              cp -r "$dir"/* "mlflow_ui_app/mlruns/$exp_name/" || echo "  Warning: Some files couldn't be copied"
            fi
          done
          
          # Copy models directory if it exists
          if [ -d "mlruns/models" ]; then
            echo "Copying registered models"
            mkdir -p mlflow_ui_app/mlruns/models
            cp -r mlruns/models/* mlflow_ui_app/mlruns/models/ || echo "Warning: Some model files couldn't be copied"
          fi
          
          # Show content of copied mlruns
          echo "Copied MLflow data structure:"
          find mlflow_ui_app/mlruns -type d -not -path "*/\.*" | sort
        else
          echo "No MLflow data to copy, setup_mlflow.py will create sample data if needed"
        fi
        
        # Replace username placeholders in README
        [ -f mlflow_ui_app/README.md ] && sed -i "s/{username}/$HF_USERNAME/g" mlflow_ui_app/README.md

    - name: Deploy MLflow UI to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        # Install and configure tools
        pip install huggingface_hub
        sudo apt-get update && sudo apt-get install -y git-lfs
        git config --global user.email "${{ secrets.EMAIL_HUGGINGFACE }}"
        git config --global user.name "${{ secrets.USERNAME_HUGGINGFACE }}"
        
        # Login to Hugging Face
        huggingface-cli login --token $HF_TOKEN
        [ -z "$HF_USERNAME" ] && echo "Error: HF_USERNAME not set in secrets" && exit 1
        
        # Try creating the space silently first, ignore errors if it already exists
        echo "Creating or checking Hugging Face Space for MLflow UI..."
        huggingface-cli repo create "spaces/$HF_USERNAME/mlflow-project-ui" --type space || echo "Space might already exist"
        
        # Setup Git repository and LFS
        cd mlflow_ui_app
        git init
        git lfs install
        
        # Configure Git LFS to track binary files
        git lfs track "*.joblib" "*.pkl" "*.h5" "*.onnx" "*.bin" "*.zip" "*.gz" "*.tar"
        git add .gitattributes
        
        # Final check for binary files that shouldn't be deployed
        find . -name "mlruns_backup.zip" -exec rm -f {} \; 2>/dev/null || true
        
        # Checkout, add all files and commit
        git checkout -b main
        git add .
        git commit -m "Deploy MLflow UI"
        
        # Push to Hugging Face
        git remote add origin "https://huggingface.co/spaces/$HF_USERNAME/mlflow-project-ui"
        git push -f "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/mlflow-project-ui" main
